namespace NewMod;

public enum CustomRPC
{
    HandleRevive,
    ApplyMissionResult,
    Drain,
    FakeBody,
    AssignMission,
    MissionSuccess,
    MissionFails,
    ApplySerum,
    Dash,
    FearPulse,
    RequestSummon,
    SuppressionDome,
    WitnessTrap,
    NotifyChampion,
    SummonNPC,
    BeaconPulse,
    DeployZone,
    StartGeneralEvent,
    EndGeneralEvent,
    TerminatorObjective,
    MirrorBladeArm,
    TerminatorFinalCountdown,
    VerifierRegisterFact,
    MirrorBladeReflect,
    StickyRequestLink,
    StickyStartLink,
    StickyEndLink,
    MarkedReveal,
    WardenSeal,
    WardenAbilityUsed,
    WardenResidualMark,
    ArbitratorJudgmentResult,
    ArbitratorJudgment,
    AbilityExchangeAssignment,
    CrismonVortexPosition,
    CrismonVortexEscape,

    // Gamemodes
    WraithSiegeRequestSummon,
    WraithSiegeSpawnNpc,
    WraithSiegeRequestRevive,
    WraithSiegeRequestBanish,
    WraithSiegeResolveNpc,
    WraithSiegeBeginDelivery,
    WraithSiegeSyncState
}